homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret my_lat
  longitude: !secret my_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London 

  customize: 
    script.radio538: 
      friendly_name: Tune
      icon: mdi:play
    media_player.roku_326673099455:
      friendly_name: Livingroom NowTV      

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

#mqtt:
#  broker: 192.168.0.250
#  discovery: true
#  discovery_prefix: smartthings

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: pi_hole
  - platform: yr
  - platform: template
    sensors:
      tv_volume:
        value_template: '{{ media_player.livingroom_tv}}'
  
#  - platform: mqtt
#    name: "Porch Door"
#    state_topic:  "smartthings/Porch Door/temperature measurement"
#    unit_of_measurement: "C"
#    retain: true

media_player:
  - platform: cast
    host: 192.168.0.56
  - platform: cast
    host: 192.168.0.13
  - platform: philips_js
    host: 192.168.0.11
    name: Livingroom TV
  - platform: roku
    host: 192.168.0.5
    name: "Livingroom NowTV"
  - platform: cast
    host: 192.168.0.6
  - platform: philips_js
    host: 192.168.0.13
    name: Bedroom TV

hive:
  username: !secret hive_username
  password: !secret hive_password


# Text to speech
tts:
  platform: google

device_tracker:
  - platform: sky_hub
    host: 192.168.0.1
#  - platform: bluetooth_le_tracker 
#  - platform: bluetooth_tracker



input_select:
  radio_station:
    name: 'Select Radio Station:'
    options:
      - BBC One
      - BBC Two
      - BBC Four
      - BBC 4 Extra
    initial: 'BBC Two'

  chromecast_radio:
    name: 'Select Speakers:'
    options:
      - Livingroom
    initial: Livingroom
    icon: mdi:speaker-wireless

script:
  radio538:
    alias: Play Radio on Chromecast Audio
#    icon: mdi:play
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.living_room
          volume_level: '0.30'
      - service: media_player.play_media
        data_template:
          entity_id: >
            {% if is_state('input_select.chromecast_radio', 'Livingroom') %} media_player.living_room
            {% endif %}
          media_content_id: >
            {% if is_state("input_select.radio_station", "BBC One") %} http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio1_mf_p
            {% elif is_state("input_select.radio_station", "BBC Two") %} http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio2_mf_p
            {% elif is_state("input_select.radio_station", "BBC Four") %} http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio4fm_mf_p
            {% elif is_state("input_select.radio_station", "BBC 4 Extra") %} http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio4extra_mf_p
            {% endif %}
          media_content_type: 'audio/mp4'


#switch:
#  platform: mqtt
#  name: "Porch Door"
#  state_topic: "smartthings/Porch Door/Contact Sensor"
#  command_topic: "smartthings/Porch Door/Contact Sensor"
#  brightness_state_topic: "smartthings/Porch Door/Battery"
#  brightness_command_topic: "smartthings/Porch Dooer/Battery"
#  payload_on: "on"
#  payload_off: "off"
#  retain: true




#group: !include groups.yaml
automation: !include automations.yaml



