##########################################
#
#  Views
#
##########################################

default_view:

Network:
  view: yes
  entities:
  - group.hardware
  - group.pihole
  - group.speedtest

Media:
  view: yes
  entities:
  - media_player.livingroom_tv
  - group.radio

Backend:
  view: yes
  entities:
  - group.automation

##########################################
#
#  Groups
#
##########################################

automation:
  name: Automations
  entities:
  - automation.auto_michelle_away
  - automation.auto_michelle_home
  - automation.auto_nik_away
  - automation.auto_nik_home
  - automation.auto_notify_porchdoor
  - automation.auto_porchdoor_open
  - automation.auto_porchdoor_timer
  - automation.update_notifications

temperatures:
  name: Temperatures
  entities:
  - sensor.hive_current_temperature
  - sensor.porch_temperature

zones:
  name: Zones
  entities:
  - binary_sensor.floorplan


pihole:
  name: Pi-hole
  entities:
  - sensor.pihole_ads_blocked_today
  - sensor.pihole_ads_percentage_blocked_today
  - sensor.pihole_dns_queries_cached
  - sensor.pihole_dns_queries_forwarded
  - sensor.pihole_dns_queries_today
  - sensor.pihole_dns_unique_clients
  - sensor.pihole_dns_unique_domains
  - sensor.pihole_domains_blocked

trackers:
  name: People
  entities:
  - device_tracker.noid1011_nexus6
  - device_tracker.michellephone
  - device_tracker.mumstablet
  - device_tracker.stephiphone
  - device_tracker.caitlinphone

doors:
  name: Doors
  entities:
  - binary_sensor.porch_door

hardware:
  name: Hardware
  entities:
  - device_tracker.pi3
  - device_tracker.desktopc6omlop
  - device_tracker.skyhd
  - device_tracker.philipshue
  - device_tracker.chromecast_livingroom
  - device_tracker.wdmycloud
  - device_tracker.tv_livingroom
  - device_tracker.speaker_livingroom
  - device_tracker.nowtv_livingroom
  - device_tracker.tv_bedroom
  - device_tracker.bt_wifi_link
  - device_tracker.smartthings_hub
  - device_tracker.bedroom_nowtv
  - device_tracker.firetv
  - device_tracker.hivehub
  - device_tracker.skytv


hive_heating:
  name: Hive Heating
  entities:
  - sensor.hive_heating_mode
  - sensor.hive_heating_boost
  - sensor.hive_heating_state
  - sensor.hive_hot_water_mode
  - sensor.hive_hot_water_boost
  - sensor.hive_hot_water_state
  - sensor.hive_target_temperature
  - sensor.hive_current_temperature
  - sensor.hive_thermostat_battery_level
  - climate.hive_heating
  - climate.hive_hotwater
  - light.hive_active_light

radio:
  name: Radio
  entities:
  - input_select.radio_station
  - input_select.chromecast_radio
  - script.radio_player

speedtest:
  name: speedtest
  entities:
  - sensor.speedtest_ping
  - sensor.speedtest_download
  - sensor.speedtest_upload

batteries:
  name: Battery Levels
  entities:
  - sensor.porch_battery